# Python & NumPy 1D, 2D, 3D Lists


## Python 1D & 2D Lists

### Basic

#### Exercise 1: Sum of diagonal Elements of a 2D List


In [ ]:
def diagonal_sum(matrix):
    # Check if the matrix is square
    if not matrix or len(matrix) != len(matrix[0]):
        raise ValueError("The matrix must be square.")
    # Calculate the sum of the main diagonal
    return sum([matrix[i][i] for i in range(len(matrix))])


matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(diagonal_sum(matrix))  # Output: 15

15


#### Exercise 2: Sort a 2D matrix by the sum of its rows


In [ ]:
def sort_matrix_by_row_sum(matrix):
    return sorted(matrix, key=lambda row: sum(row))


matrix = [[4, 2, 7], [1, 5, 6], [3, 8, 2]]
print(sort_matrix_by_row_sum(matrix))

[[1, 5, 6], [4, 2, 7], [3, 8, 2]]


#### Exercise 3: Inventory Management


A company has a list of inventory items for various products. The inventory information includes the product name, quantity in stock, and the selling price of each product. The company wants to calculate the total value of its inventory.

The company's inventory list is represented by a matrix of size nx3, where n is the number of different products. The columns in the matrix represent the product name, quantity in stock, and selling price of each product.

For example, the inventory matrix might look like this:
Inventory:

```
|    Name    | Quantity | Price |
|  Product 1 |    10    |   5.0   |
|  Product 2 |    5     |   2.5   |
|  Product 3 |    3     |   8.0   |
```

- Calculate the total quantity of inventory for all products.
- Calculate the inventory value of each product by multiplying the quantity with the selling price of the corresponding product.
- Calculate the total value of the entire inventory.

Write equations or code to solve each of the above exercises.


In [ ]:
# Inventory matrix
inventory = [["Product 1", 10, 5.0], ["Product 2", 5, 2.5], ["Product 3", 3, 8.0]]

# Calculate the total quantity of inventory for all products
total_quantity = sum(item[1] for item in inventory)
print("Total inventory quantity:", total_quantity)

# Calculate the inventory value of each product
product_values = [item[1] * item[2] for item in inventory]
print("Inventory value of each product:", product_values)

# Calculate the total value of the entire inventory
total_value = sum(product_values)
print("Total inventory value:", total_value)

Total inventory quantity: 18
Inventory value of each product: [50.0, 12.5, 24.0]
Total inventory value: 86.5


## Python 3D List


### Basic


#### Exercise 1: Find maximum value in a 3D list


In [ ]:
def find_max(list_3d):
    return max(max(list_1d) for list_2d in list_3d for list_1d in list_2d if list_1d)


list_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
print(find_max(list_3d))

12


#### Exercise 2: Flatten a 3D list into a 1D list


##### Solution 1: Using Loops


In [ ]:
# Use 3 nested loops to flatten the 3D list
def flatten_3d_list(list_3d):
    # Initialize an empty list to hold the flattened elements
    flat_list = []
    # Iterate through each 2D list in the 3D list
    for list_2d in list_3d:
        # Iterate through each 1D list in the 2D list
        for list_1d in list_2d:
            # Iterate through each item in the 1D list and append it to the flat_list
            for item in list_1d:
                flat_list.append(item)
    return flat_list


list_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
print(flatten_3d_list(list_3d))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


##### Solution 2: Using List Comprehension


In [ ]:
def flatten_3d_list(list_3d):
    return [item for list_2d in list_3d for list_1d in list_2d for item in list_1d]


list_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
print(flatten_3d_list(list_3d))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


#### Exercise 3: Rotate a 3D list (matrix) 90 degrees clockwise


In [ ]:
def rotate_3d_clockwise(list_3d):
    # zip(*list_3d) transposes the 3D list, and [list(reversed(x)) for x in ...] reverses each sublist to achieve a 90-degree clockwise rotation
    # use * to unpack the list_3d for zip function, which groups elements from each sublist together
    # if not using *, zip would treat the entire list_3d as a single argument, resulting in incorrect grouping
    return [list(reversed(x)) for x in zip(*list_3d)]


list_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
print(rotate_3d_clockwise(list_3d))

[[[7, 8, 9], [1, 2, 3]], [[10, 11, 12], [4, 5, 6]]]


## Numpy 1D, 2D, 3D List

Run this cell to load numpy:


In [2]:
import numpy as np

### Numpy 1D List


#### Exercise 1: Create 5 elements array

In [ ]:
my_arr = np.array([1, 2, 3, 4, 5])
print(my_arr)

[1 2 3 4 5]


#### Exercise 2: Sum of all elements in a 1D array

In [ ]:
my_arr = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(my_arr)  # renamed from 'sum' to avoid shadowing
print(total_sum)

15


#### Exercise 3: Min/Max

In [ ]:
my_arr = np.array([1, 2, 3, 4, 5])
min_value, max_value = np.min(my_arr), np.max(my_arr)
print(min_value, max_value)

1 5


#### Exercise 4: Mean/Median of a 1D array

In [ ]:
my_arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(my_arr)
median_value = np.median(my_arr)
print(mean_value, median_value)

3.0


#### Exercise 5: Sort ascending/descending order a 1D array

##### Solution 1: Using np.sort() and slicing


In [ ]:
my_arr = np.array([1, 2, 3, 4, 5])
ascending = np.sort(my_arr)
descending = ascending[::-1]
print(ascending, descending)

[1 2 3 4 5] [5 4 3 2 1]


##### Solution 2: Using np.sort() and np.flip()


In [10]:
descending = np.flip(ascending)
print(ascending, descending)

[1 2 3 4 5] [5 4 3 2 1]


#### Exercise 6: Sum of elements at odd/even indices in a 1D array

In [ ]:
my_arr = np.array([1, 2, 3, 4, 5])
sum_even_indices = np.sum(my_arr[::2])   # indices 0,2,4
sum_odd_indices = np.sum(my_arr[1::2])    # indices 1,3
print(sum_even_indices, sum_odd_indices)

9 6


#### Exercise 7: Find even numbers and their summation in a 1D array

In [ ]:
my_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even = my_arr[my_arr % 2 == 0]
even_sum = np.sum(even)
print(even_sum, even)

30 [ 2  4  6  8 10]


#### Exercise 8: Sum of prime numbers in a 1D array

`np.vectorize()`


In [ ]:
import math


def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True


my_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
primes = my_arr[np.vectorize(is_prime)(my_arr)]
primes_sum = np.sum(primes)
print(primes, primes_sum)

[2 3 5 7] 17


#### Exercise 9: Sum of positive and product of negative numbers in a 1D array

`np.sum()`, `np.prod()`


In [ ]:
my_arr = np.array([-1, 2, -3, 4, -5, 6])
positive_sum = np.sum(my_arr[my_arr > 0])
negative_product = np.prod(my_arr[my_arr < 0])  # renamed from negative_sum
print(positive_sum, negative_product)

12 -15


#### Exercise 10: Sum of elements after removing duplicates in a 1D array

`np.unique()`

In [20]:
my_array = [1, 2, 3, 2, 4, 5, 1, 6, 7, 8, 5]
unique = np.unique(my_array)
unique_sum = np.sum(unique)
print(unique, unique_sum)

[1 2 3 4 5 6 7 8] 36


### Numpy 2D List

#### Basic

#### Exercise 1: Sum of elements in a 2D array

In [21]:
my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.sum(my_array))

45


#### Exercise 2: Min/Max in a 2D array

In [22]:
my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.min(my_array), np.max(my_array))

1 9


#### Exercise 3: Mean/Median in a 2D array

In [ ]:
my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.mean(my_array), np.median(my_array))  # added median

5.0


#### Exercise 4: Sort rows in a 2D array

In [ ]:
my_array = [[5, 3, 1], [4, 2, 6], [9, 7, 8]]
ascending = np.sort(my_array, axis=1)
descending = ascending[:, ::-1]  # per-row descending
print(ascending)
print(descending)

[[1 3 5]
 [2 4 6]
 [7 8 9]]
[[9 8 7]
 [6 4 2]
 [5 3 1]]


#### Exercise 5: Sum of each row and sum of rows sum in a 2D array

In [27]:
my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
rows_sum = np.sum(my_array, axis=1)
rows_sum_sum = np.sum(rows_sum)
print(rows_sum, rows_sum_sum)

[ 6 15 24] 45


#### Exercise 6: Sum of each column and sum of columns sum in a 2D array

In [31]:
my_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
columns_sum = np.sum(my_array, axis=0)
total_sum = np.sum(columns_sum)
print(columns_sum, total_sum)

[12 15 18] 45


#### Exercise 7: Find max and its position in a 2D array

In [ ]:
# np.unravel_index(np.argmax(my_array), my_array.shape) to get the 2D index of the max value
my_array = np.array([[1, 2, 3], [4, 9, 6], [7, 8, 5]])
max_value = np.max(my_array)
max_value_index = np.unravel_index(np.argmax(my_array), my_array.shape)
print(max_value, max_value_index)

9 (np.int64(1), np.int64(1))
